services:
  app:
    image: ghcr.io/andriawan/laravel-best-practice:${TAG:-latest}
    container_name: ${APP_NAME:-demo}
    ports:
      - '${APP_PORT:-8080}:80'
      - '${APP_PORT_HTTPS:-8443}:443'
      - '${APP_PORT_HTTPS:-8443}:443/udp'
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env

volumes:
  caddy_data:
  caddy_config: